apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vnp32whkv-go
  janus-idp.io/tekton: vnp32whkv-go
  backstage.io/kubernetes-id: vnp32whkv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vnp32whkv-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
